config/routes.rb
Rails.application.routes.draw do
  root 'linkedin_posts#index'

  get "/auth/:provider", to: "sessions#omniauth_login", as: :oauth_login
  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  delete "/logout", to: "sessions#destroy", as: :signout

  resources :linkedin_posts, only: [:index, :create]

  resources :tweets, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @name = "abc"
    end
end

app/controllers/linkedin_posts_controller.rb
require 'net/http'
require 'json'

class LinkedinPostsController < ApplicationController
  def index
    # Render the form in index.html.erb
  end

  def create
    post_content = params[:post_content]
    
    # Retrieve the access token stored in the session
    access_token = session[:linkedin_token]
    
    if access_token.nil?
      flash[:alert] = "Authentication required. Please log in with LinkedIn."
      redirect_to root_path and return
    end

    # Prepare the post data
    post_data = {
      "author": "urn:li:organization:105966173",  # Change to your LinkedIn organization ID
      "commentary": post_content,
      "visibility": "PUBLIC",
      "distribution": {
        "feedDistribution": "MAIN_FEED",
        "targetEntities": [],
        "thirdPartyDistributionChannels": []
      },
      "lifecycleState": "PUBLISHED",
      "isReshareDisabledByAuthor": false
    }

    # Make the API request
    response = LinkedInService.new(access_token).create_post(post_data)

    if response.code.to_i == 201
      flash[:notice] = "Post successfully created on LinkedIn!"
    else
      flash[:alert] = "Failed to post on LinkedIn: #{response.body}"
    end

    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    
    if auth.present?
      user = User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
        u.name = auth['info']['name']
        u.nickname = auth['info']['nickname']
        u.image = auth['info']['image']
        u.token = auth['credentials']['token']
        u.secret = auth['credentials']['secret'] if auth['credentials']['secret'].present?
      end

      session[:user_id] = user.id
      flash[:notice] = "Signed in successfully with #{auth['provider'].capitalize}!"
    else
      flash[:alert] = "Authentication failed! No data received."
    end

    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Signed out successfully!"
    redirect_to root_path
  end

  def failure
    flash[:alert] = "Authentication failed!"
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
  end

  def create
    if current_user.token.present? && current_user.secret.present?
      client = Twitter::REST::Client.new do |config|
        config.consumer_key        = ENV['TWITTER_API_KEY']
        config.consumer_secret     = ENV['TWITTER_API_SECRET']
        config.access_token        = current_user.token
        config.access_token_secret = current_user.secret
      end

      begin
        client.update(params[:message])
        flash[:notice] = "Tweet posted successfully!"
      rescue Twitter::Error => e
        flash[:alert] = "Failed to post tweet: #{e.message}"
      end
    else
      flash[:alert] = "You need to authenticate with Twitter first!"
    end

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/linkedin_posts_helper.rb
module LinkedinPostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<h1>
    Hello World
    <%= @name%>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Social Post" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/linkedin_posts/create.html.erb
<h1>LinkedinPosts#create</h1>
<p>Find me in app/views/linkedin_posts/create.html.erb</p>

app/views/linkedin_posts/index.html.erb
<h1>Post to LinkedIn</h1>

<%= form_with url: linkedin_posts_path, method: :post do %>
  <div>
    <%= label_tag :post_content, "Enter your post:" %><br>
    <%= text_area_tag :post_content, nil, rows: 5, cols: 40 %>
  </div>
  <br>
  <%= submit_tag "Post to LinkedIn" %>
<% end %>

<% if session[:linkedin_token] %>
  <p>✅ You are logged in with LinkedIn!</p>
  <%= button_to "Logout", logout_path, method: :delete %>
<% else %>
  <%= link_to "Login with LinkedIn", "/auth/linkedin", class: "button" %>
<% end %>

<% if flash[:notice] %>
  <p style="color: green;"><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
  <p style="color: red;"><%= flash[:alert] %></p>
<% end %>
<br>
<br>
<br>
<%= link_to "Post to Twitter", new_tweet_path, class: "button", style: "background-color: #1DA1F2; color: white; padding: 10px; border-radius: 5px; text-decoration: none;" %>

app/views/tweets/new.html.erb
<h2>Post a Tweet</h2>
<%= form_with url: tweets_path, method: :post do |f| %>
  <%= f.text_area :tweet, placeholder: "What's happening?" %>
  <%= f.submit "Tweet" %>
<% end %>